version: "3.9"

services:
  nest_first_dev:
    build:
      context: .
      dockerfile: apps/nest_first/Dockerfile.dev
    image: org_nest_first_dev:latest
    profiles: ["dev"]
    working_dir: /workspace
    volumes:
      - ./:/workspace:cached
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: sh -c "npx nx run @org/nest_first:serve --configuration=development"
    stdin_open: true
    tty: true
